connections:
  default:
    host: 'localhost'
    port: 5672
    login: 'guest'
    password: 'guest'
producers:
  extractor:
    connection: default
    exchange_options: {name: 'extractor_exchange', type: direct, durable: 1, passive: 0}
consumers:
  extractor:
    connection: default
    queue_options:
      name: 'extractor_queue'
      durable: 1
      autodelete: 0
      binding: {name: 'extractor_exchange', routing-keys: ''}
